apollo:
  bootstrap:
    enabled: true
    namespaces: application #如果有多个，用逗号拼接

app:
  id: # TODO
  apiKey: # TODO

spring:
  application:
    name: ${project.name}

management:
  endpoints:
    web:
      #actuator基础路径
      base-path: /
  endpoint:
    info:
      #屏蔽info接口
      enabled: true
    health:
      show-details: always

log_path: ${logger.path}
