#文档： https://www.yuque.com/mamcharge_knowledgebase/iiubck/vov16v
mam:
  mongodb:
    options:
      enable-write-class: false #是否写入类型
      application-name: test # 应用名称，方便mongo-server端日志记录区分（未测）
      heartbeat-frequency: 10000 # 心跳间隔
    datasources:
      - uri: mongodb://127.0.0.1:20000/test # 多数据源【1】-地址
        template-name: test-tpl # mongoTemplate bean别名
        prefix: test # 数据源名称，默认会注册两个bean: test-mongoClient(客户端),
        # test-mongoTemplate(mongoTemplate)
      - uri: mongodb://127.0.0.1:20000/itest # 多数据源【2】-地址
        prefix: second # 数据源名称
  #文档 https://www.yuque.com/mamcharge_knowledgebase/iiubck/mmafpy
  cache:
    strategy: rediss #缓存策略，目前包括(rediss:单机,redisc:集群)，若具体的profile里面已经配置了,
    #则以profile中配置的为准,若都没有配置默认为集群策略
    profiles: dev
    redis:
      host: 127.0.0.1
      port: 6379
      # password:    #redis服务端密码,若有需要设置
      #maxAttempts: 5   #出现异常重连次数，就是说连接其中某个节点失败后，重连其他节点的次数，不写默认5次
      # cluster:
      #  nodes: 39.100.137.55:6379,39.100.137.55:6389,39.100.137.55:6380,39.100.137.55:6390,
      #    39.100.137.55:6381,39.100.137.55:6391
      timeout: 3000 #连接超时、操作超时时间
      pool:
        max-idle: 1    #连接池中的最大空闲连接
        min-idle: 1    #连接池中的最小空闲连接
        max-wait: 3000 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-active: 2  #连接池最大连接数（使用负值表示没有限制）
    key-serializer: com.mamcharge.cache.test.StringRedisSerializer
    hash-key-serializer: com.mamcharge.cache.test.StringRedisSerializer
    value-serializer: com.mamcharge.cache.test.StringRedisSerializer
    interceptors: com.mamcharge.cache.test.RedisOperationsInterceptorPrint
    interceptorMethod: stringGet